import { IMenu } from '../core/models/core.models';

export const ALL_MENUS: IMenu[] = [
  // Public menus
  {
    id: 'skip',
    label: 'Skip To Main Content',
    icon: 'bi-arrow-right-short',
    route: '/skip',
    order: 0,
    isPublic: true,
  },
  {
    id: 'medicaid',
    label: 'Medicaid Home',
    icon: 'bi-house-door',
    route: '/medicaid',
    order: 1,
    isPublic: true,
  },
  {
    id: 'home',
    label: 'Home',
    icon: 'bi-house',
    route: '/home',
    order: 2,
    isPublic: true,
  },

  // Protected menus
  {
    id: 'myqueue',
    label: 'My Queue',
    icon: 'bi-list-task',
    route: '/myqueue',
    order: 3,
  },
  {
    id: 'providersearch',
    label: 'Provider Search',
    icon: 'bi-search',
    route: '/providersearch',
    order: 4,
  },
  {
    id: 'ownersearch',
    label: 'Owner Search',
    icon: 'bi-person-search',
    route: '/ownersearch',
    order: 5,
  },
  {
    id: 'providerdirectory',
    label: 'Provider Directory',
    icon: 'bi-people',
    route: '/providerdirectory',
    order: 6,
  },
  {
    id: 'gissearch',
    label: 'Provider Search - GIS',
    icon: 'bi-geo-alt',
    route: '/gissearch',
    order: 7,
  },

  // More protected menus
  {
    id: 'profile',
    label: 'My Profile',
    icon: 'bi-person-circle',
    route: '/profile',
    order: 8,
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'bi-speedometer2',
    route: '/dashboard',
    order: 9,
  },
  {
    id: 'sitevisit',
    label: 'Site Visit Assignment',
    icon: 'bi-map',
    route: '/sitevisit',
    order: 10,
  },
  {
    id: 'transaction',
    label: 'Transaction Search',
    icon: 'bi-search-heart',
    route: '/transaction',
    order: 11,
  },
  {
    id: 'useradmin',
    label: 'User Administration',
    icon: 'bi-people-fill',
    route: '/useradmin',
    order: 12,
  },
  {
    id: 'refdata',
    label: 'Reference Data',
    icon: 'bi-journal-text',
    route: '/refdata',
    order: 13,
  },
  {
    id: 'workflow',
    label: 'Workflow Engine',
    icon: 'bi-arrow-repeat',
    route: '/workflow',
    order: 14,
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: 'bi-bar-chart-line',
    route: '/reports',
    order: 15,
  },
  {
    id: 'apm',
    label: 'Alternative Payment Model Formation',
    icon: 'bi-award',
    route: '/apm',
    order: 16,
  },
  {
    id: 'ordering',
    label: 'Ordering, Referring and Prescribing Search',
    icon: 'bi-pencil-square',
    route: '/ordering',
    order: 17,
  },
  {
    id: 'eligibility',
    label: 'Recipient Eligibility',
    icon: 'bi-person-check',
    route: '/eligibility',
    order: 18,
  },
  {
    id: 'specialty',
    label: 'Provider Specialty Search',
    icon: 'bi-briefcase',
    route: '/specialty',
    order: 19,
  },
  {
    id: 'education',
    label: 'Provider Ed & Training Resources',
    icon: 'bi-book',
    route: '/education',
    order: 20,
  },
];
