import { IMenu } from '../core/models/core.models';

export const ALL_MENUS: IMenu[] = [
  // Public menus
  {
    id: 'skip',
    label: 'Skip To Main Content',
    icon: 'bi-arrow-right-short',
    route: '/skip',
    order: 0,
    isPublic: true,
    permissionCode: 'SKIP.VIEW',
  },
  {
    id: 'medicaid',
    label: 'Medicaid Home',
    icon: 'bi-house-door',
    route: '/medicaidhome',
    order: 1,
    isPublic: true,
    permissionCode: 'MEDICAID.VIEW',
  },
  {
    id: 'home',
    label: 'Home',
    icon: 'bi-house',
    route: '/home',
    order: 2,
    isPublic: true,
    permissionCode: 'HOME.VIEW',
  },

  // Protected menus (all have isPublic: false)
  {
    id: 'myqueue',
    label: 'My Queue',
    icon: 'bi-list-task',
    route: '/myqueue',
    order: 3,
    isPublic: false,
    permissionCode: 'MYQUEUE.VIEW',
  },
  {
    id: 'providersearch',
    label: 'Provider Search',
    icon: 'bi-search',
    route: '/providersearch',
    order: 4,
    isPublic: false,
    permissionCode: 'PROVIDERSEARCH.VIEW',
  },
  {
    id: 'ownersearch',
    label: 'Owner Search',
    icon: 'bi-person-search',
    route: '/ownersearch',
    order: 5,
    isPublic: false,
    permissionCode: 'OWNERSEARCH.VIEW',
  },
  {
    id: 'providerdirectory',
    label: 'Provider Directory',
    icon: 'bi-people',
    route: '/providerdirectory',
    order: 6,
    isPublic: true,
    permissionCode: 'PROVIDERDIRECTORY.VIEW',
  },
  {
    id: 'gissearch',
    label: 'Provider Search - GIS',
    icon: 'bi-geo-alt',
    route: '/gissearch',
    order: 7,
    isPublic: true,
    permissionCode: 'GISSEARCH.VIEW',
  },
  {
    id: 'profile',
    label: 'My Profile',
    icon: 'bi-person-circle',
    route: '/profile',
    order: 8,
    isPublic: false,
    permissionCode: 'PROFILE.VIEW',
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'bi-speedometer2',
    route: '/dashboard',
    order: 9,
    isPublic: false,
    permissionCode: 'DASHBOARD.VIEW',
  },
  {
    id: 'sitevisit',
    label: 'Site Visit Assignment',
    icon: 'bi-map',
    route: '/sitevisit',
    order: 10,
    isPublic: false,
    permissionCode: 'SITEVISIT.VIEW',
  },
  {
    id: 'transaction',
    label: 'Transaction Search',
    icon: 'bi-search-heart',
    route: '/transaction',
    order: 11,
    isPublic: false,
    permissionCode: 'TRANSACTION.VIEW',
  },
  {
    id: 'useradmin',
    label: 'User Administration',
    icon: 'bi-people-fill',
    route: '/useradmin',
    order: 12,
    isPublic: false,
    permissionCode: 'USERADMIN.VIEW',
  },
  {
    id: 'refdata',
    label: 'Reference Data',
    icon: 'bi-journal-text',
    route: '/refdata',
    order: 13,
    isPublic: false,
    permissionCode: 'REFDATA.VIEW',
  },
  {
    id: 'workflow',
    label: 'Workflow Engine',
    icon: 'bi-arrow-repeat',
    route: '/workflow',
    order: 14,
    isPublic: false,
    permissionCode: 'WORKFLOW.VIEW',
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: 'bi-bar-chart-line',
    route: '/reports',
    order: 15,
    isPublic: false,
    permissionCode: 'REPORTS.VIEW',
  },
  {
    id: 'apm',
    label: 'Alternative Payment Model Formation',
    icon: 'bi-award',
    route: '/apm',
    order: 16,
    isPublic: false,
    permissionCode: 'APM.VIEW',
  },
  {
    id: 'ordering',
    label: 'Ordering, Referring and Prescribing Search',
    icon: 'bi-pencil-square',
    route: '/ordering',
    order: 17,
    isPublic: false,
    permissionCode: 'ORDERING.VIEW',
  },
  {
    id: 'eligibility',
    label: 'Recipient Eligibility',
    icon: 'bi-person-check',
    route: '/eligibility',
    order: 18,
    isPublic: false,
    permissionCode: 'ELIGIBILITY.VIEW',
  },
  {
    id: 'specialty',
    label: 'Provider Specialty Search',
    icon: 'bi-briefcase',
    route: '/specialty',
    order: 19,
    isPublic: false,
    permissionCode: 'SPECIALTY.VIEW',
  },
  {
    id: 'providertraining',
    label: 'Provider Ed & Training Resources',
    icon: 'bi-book',
    route: '/provider-training',
    order: 20,
    isPublic: true,
    permissionCode: '',
  },
  {
    id: 'contactus',
    label: 'Contact Us',
    icon: 'bi-envelope',
    route: '/contactus',
    order: 21,
    isPublic: true,
    permissionCode: '',
  },
  {
    id: 'feeschedule',
    label: 'Fee Schedule',
    icon: 'bi-file-earmark-spreadsheet',
    route: '/feeschedule',
    order: 22,
    isPublic: true,
    permissionCode: '',
  },
];
